name: uglian
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true
